"""remove group stuff

Revision ID: 0f204414e74a
Revises: d491f471e582
Create Date: 2026-03-17 23:25:36.403181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f204414e74a'
down_revision: Union[str, Sequence[str], None] = 'd491f471e582'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'name')
    op.drop_column('conversations', 'is_group')
    op.drop_column('conversations', 'avatar_url')
    op.drop_column('conversations', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('conversations', sa.Column('avatar_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('conversations', sa.Column('is_group', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('conversations', sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
