"""add return fields to order

Revision ID: 3b25cf37b9fa
Revises: 6e2bdfc3f051
Create Date: 2026-03-22 18:48:19.052622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b25cf37b9fa'
down_revision: Union[str, Sequence[str], None] = '6e2bdfc3f051'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('return_reason', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('return_note', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'return_note')
    op.drop_column('orders', 'return_reason')
    # ### end Alembic commands ###
