"""make ai_chat user_id non nullable

Revision ID: 8d481b09966b
Revises: 0f204414e74a
Create Date: 2026-03-17 23:58:10.317120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d481b09966b'
down_revision: Union[str, Sequence[str], None] = '0f204414e74a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ai_chat_sessions', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(op.f('ai_chat_sessions_user_id_fkey'), 'ai_chat_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'ai_chat_sessions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ai_chat_sessions', type_='foreignkey')
    op.create_foreign_key(op.f('ai_chat_sessions_user_id_fkey'), 'ai_chat_sessions', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.alter_column('ai_chat_sessions', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
