"""make address nullable

Revision ID: f348af9eb3dc
Revises: 4932f694cf1b
Create Date: 2026-03-17 15:19:17.864912

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f348af9eb3dc"
down_revision: Union[str, Sequence[str], None] = "4932f694cf1b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "customer_profiles", "address", existing_type=sa.TEXT(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "customer_profiles", "address", existing_type=sa.TEXT(), nullable=False
    )
    # ### end Alembic commands ###
